apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook
  labels:
    app: webhook
rules:
- apiGroups:
  - "*"
  resources:
  - pods
  - secrets
  verbs:
  - "*"
- apiGroups:
  - data.kuda.io
  resources:
  - datasets
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-init
  labels:
    app: webhook-init
rules:
- apiGroups:
  - "*"
  resources:
  - secrets
  verbs:
  - create
  - update
  - get
  - patch
  - list
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approval
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - certificates.k8s.io
  resources:
  - signers
  resourceNames:
  - kubernetes.io/kubelet-serving
  verbs:
  - approve
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - create
  - update
  - patch
