name: kuda

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.13

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./cover.out
